name: Publish package

on:
  push:
    # branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 10.32.1
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
          registry-url: hhttps://npm.pkg.github.com
      - name: Configure npm auth
        run: |
          cat <<EOF > ~/.npmrc
          @kaon-robotics:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Check
        run: pnpm check

      - id: package
        name: Get package version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
      # - run: |
      #     echo "Token length: ${#NODE_AUTH_TOKEN}"
      #     printf %s "$NODE_AUTH_TOKEN" | sha256sum
      - name: Publish package
        run: |
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare next version
        if: github.ref_name == 'main'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git rev-parse "v${{ steps.package.outputs.version }}" >/dev/null 2>&1 || \
            git tag "v${{ steps.package.outputs.version }}" "$GITHUB_SHA"
          pnpm version patch --no-git-tag-version
          git add package.json
          git commit -m "chore: prepare next patch version"
          git push --atomic origin HEAD:main "v${{ steps.package.outputs.version }}"